config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'canteens/index'
  get 'canteens/:canteen_id/users', to: 'users#index_for_canteen_admin', as: 'canteen_admins'
  devise_for :users
  devise_scope :user do 
    match "/canteens/:canteen_id/invitations/new", :to => "users/invitations#new", :via => "get", :as => "new_canteen_invitation"
    #match "/canteens/:canteen_id/invitations/create", :to => "users/invitations#create", :via => "post", :as => "create_canteen_invitation"
  end
  root 'users#index'

  resources :csv_files
  resources :canteens do
    resources :users
    resources :customers do
      resources :attendance_details
      resource :membership do
        resources :payments
      end
  	end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance_detail.rb
class AttendanceDetail < ApplicationRecord
  belongs_to :customer

  before_create do
    self.no_of_meals = 0
  end
end

app/models/canteen.rb
class Canteen < ApplicationRecord
	validates :name, presence: true, length: { minimum: 4 }
	has_many :users
	has_many :customers
end

app/models/csv_file.rb
class CsvFile < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
	validates :name, :age, :phone_no, presence: true
	has_many :attendance_details
	has_one :membership
  belongs_to :canteen
end

app/models/membership.rb
class Membership < ApplicationRecord
	has_many :payments
  belongs_to :customer
end

app/models/payment.rb
class Payment < ApplicationRecord
	validates :amounts, numericality: { only_integer: true }
  belongs_to :membership
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :invitable
	validates :name, presence: true
	validates :role, inclusion: { in: %w(Admin CanteenAdmin), message: "%{value} is not a valid user" }
  belongs_to :canteen, optional: true

  before_validation do
  	self.role = 'CanteenAdmin' if role.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(user)
 		canteens_index_path
	end

  def after_invite_path_for(user)
    canteens_index_path
  end

  def after_accept_path_for(user)
    accept_user_invitation_path
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit(:invite, keys: [:email, :canteen_id])
    devise_parameter_sanitizer.permit(:accept_invitation, keys: [:name, :password, :password_confirmation])
  end
end

app/controllers/canteens_controller.rb
class CanteensController < ApplicationController
	def index
		if current_user.role == 'Admin'
			@canteens = Canteen.all
		else current_user.role == 'CanteenAdmin'
			@cid = current_user.canteen_id
			@canteens = Canteen.find_by(id: @cid)
		end
	end

	def show
		@canteen = Canteen.find(params[:id])
	end
	
	def new
		@canteen = Canteen.new
	end

	def edit
  	@canteen = Canteen.find(params[:id])
	end

	def create
		@canteen = Canteen.new(canteen_params)
 
  	if @canteen.save
    	redirect_to canteens_path
  	else
    	render 'new'
  	end
	end

	def update
  	@canteen = Canteen.find(params[:id])
 
  	if @canteen.update(canteen_params)
    	redirect_to canteens_path
  	else
    	render 'edit'
  	end
	end

	def destroy
  	@canteen = Canteen.find(params[:id])
  	@canteen.destroy
 
  	redirect_to canteens_path
	end

	private
  def canteen_params
    params.require(:canteen).permit(:name, :address)
  end
end

app/controllers/csv_files_controller.rb
class CsvFilesController < ApplicationController
	def index
    @csv_files = CsvFile.all
  end

  def show
    @csv_file = CsvFile.find(params[:id])
  end
  
  def new
    @csv_file = CsvFile.new
  end

  def create
    @csv_file = CsvFile.new(csv_file_params) do |t|
      if params[:csv_file][:data]
        t.data      = params[:csv_file][:data].read
        t.filename  = params[:csv_file][:data].original_filename
        t.mime_type = params[:csv_file][:data].content_type
      end
    end
    
    if @csv_file.save
    	InviteAdminsJob.perform_now(@csv_file.id)
      flash[:success] = "File imported successfully"
      redirect_to canteens_index_path
    else
      render 'new'
    end
  end
  
  def destroy
    @csv_file = CsvFile.find(params[:id])
    @csv_file.destroy
    redirect_to(csv_files_path)
  end

  private
  	def csv_file_params
			params.require(:csv_file).permit(:name, :data)
		end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

	def index
		@canteen = Canteen.find(params[:canteen_id])
		@customers = @canteen.customers.all
	end

	def new
		@canteen = Canteen.find(params[:canteen_id])
		@customer = @canteen.customers.new
	end

	def show
		@canteen = Canteen.find(params[:canteen_id])
		@customer = @canteen.customers.find(params[:id])
	end

	def edit
		@canteen = Canteen.find(params[:canteen_id])
		@customer = @canteen.customers.find(params[:id])
	end

	def create
		@canteen = Canteen.find(params[:canteen_id])
		@customer = @canteen.customers.new(customer_params)
		if @customer.save
			redirect_to @customer
		else
			render 'new'
		end
	end

	def update
		@canteen = Canteen.find(params[:canteen_id])
		@customer = @canteen.customers.find(params[:id])

		if @customer.update(customer_params)
    	redirect_to canteen_customers_path(@canteen)
  	else
    	render 'edit'
  	end
	end

	def destroy
		@canteen = Canteen.find(params[:canteen_id])
  	@customer = @canteen.customers.find(params[:id])
  	@customer.destroy
  	redirect_to canteen_customers_path(@canteen)
	end

	private
  def customer_params
    params.require(:customer).permit(:name, :age, :phone_no, :address)
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
	def index
		@memberships = Canteen.Membership.all
	end

	def create

	end
	def new
		@canteen = Canteen.find(params[:canteen_id])
		redirect_to new_canteen_membership_customer_path()
		#@membership = @canteen.Membership.create()
	end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def index_for_canteen_admin
  	@canteen = Canteen.find(params[:canteen_id])
  	@users = @canteen.users.all
  end

  def new
  	@canteen = Canteen.find(params[:canteen_id])
  	@user = @canteen.users.new
  end

  def create
  	@canteen = Canteen.find(params[:canteen_id])
    @user = @canteen.users.create(user_params)
    redirect_to canteens_path
  end

  def edit
  	@canteen = Canteen.find(params[:canteen_id])
  	@user = @canteen.users.find(params[:id])
  end

  def update
  	@canteen = Canteen.find(params[:canteen_id])
 		@user = @canteen.users.find(params[:id])
    if @user.update(user_params)
      redirect_to canteen_admins_path(@canteen)
  	else
    	render 'edit'
  	end
  end

  def destroy
  	@canteen = Canteen.find(params[:canteen_id])
  	@user = @canteen.users.find(params[:id])
  	@user.destroy
 
  	redirect_to canteen_admins_path(@canteen)
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/canteens_helper.rb
module CanteensHelper
end

app/helpers/csv_files_helper.rb
module CsvFilesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/canteens/_form.html.haml
= simple_form_for @canteen do |f|
  = f.input :name
  = f.input :address
  = f.button :submit, 'Save canteen', class: 'btn btn-sm btn-success'
  = link_to 'Back', canteens_path, class: 'btn btn-sm btn-dark'

app/views/canteens/edit.html.haml
.container
  .row
    .col-3
    %h3 Edit Canteen
  .row
    .col-3
    .col-5
      = render 'form'
    .col-4

app/views/canteens/index.html.haml
.container
  .row.mb-3.mt-5
    .col-7
      %h3 Listing Canteens
    .col-5
      = link_to 'Import admins through csv', new_csv_file_path, class: 'btn btn-primary btn-md'
      = link_to 'Create Canteen', new_canteen_path, class: 'btn btn-primary btn-md'
    
  %table.table.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Address
        %th No. of users
        %th Actions
    %tbody
      - @canteens.each do |canteen|
        %tr
          %td= canteen.name
          %td= canteen.address
          %td
          %td 
            =link_to 'Edit', edit_canteen_path(canteen), class: 'btn btn-secondary btn-sm' 
            =link_to 'Destroy', canteen_path(canteen), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'
            = link_to 'Canteen Admin', canteen_admins_path(canteen), class: 'btn btn-info btn-sm'
            = link_to 'Customers', canteen_customers_path(canteen), class: 'btn btn-info btn-sm'

app/views/canteens/new.html.haml
.container
  .row.mt-5
    .col-3
    %h3 New Canteen
  .row
    .col-3
    .col-5
      = render 'form'
    .col-4

app/views/canteens/show.html.haml
%p
  %strong Name:
  = @canteen.name
= link_to 'Edit', edit_canteen_path(@canteen)
= link_to 'Back', canteens_path

app/views/csv_files/_form.html.haml
= simple_form_for(@csv_file, :html => {:enctype => "multipart/alternative"}) do |f|
  = f.input :name
  = f.file_field :data
  = f.button :submit, 'Import', class: 'btn btn-sm btn-success'
  = link_to 'Back', canteens_path, class: 'btn btn-sm btn-dark'

app/views/csv_files/new.html.haml
.container
  .row.mt-4
    .col-3
    %h3 New File
  .row
    .col-3
    .col-5
      = render 'form'
    .col-4

app/views/customers/_form.html.haml
= simple_form_for [@canteen, @customer] do |f|
  = f.input :name
  = f.input :age
  = f.input :phone_no
  = f.input :address
  = f.button :submit, 'Save customer', class: 'btn btn-sm btn-success'
  =link_to 'Back', canteen_customers_path(@canteen), class: 'btn btn-dark btn-sm'

app/views/customers/edit.html.haml
.container
  .row
    .col-3
    %h3 Edit Customer
  .row
    .col-3
    .col-5
      = render 'form'
    .col-4

app/views/customers/index.html.haml
.container
  .row.mb-3.mt-5
    .col-7
      %h3 Listing Customers
    .col-5
      = link_to 'Create Customer', new_canteen_customer_path, class: 'btn btn-primary btn-md'
    
  %table.table.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Age
        %th Phone_no
        %th Address
        %th Actions
    %tbody
      - @customers.each do |customer|
        %tr
          %td= customer.name
          %td= customer.age
          %td= customer.phone_no
          %td= customer.address
          %td
            =link_to 'Edit', edit_canteen_customer_path(@canteen, customer), class: 'btn btn-secondary btn-sm' 
            =link_to 'Destroy', canteen_path(@canteen, customer), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'
  =link_to 'Back', canteens_index_path, class: 'btn btn-dark btn-sm'

app/views/customers/new.html.haml
.container
  .row.mt-4
    .col-3
    %h3 New Customer
  .row
    .col-3
    .col-5
      = render 'form'
    .col-4

app/views/customers/show.html.haml
.container
  .row
    .col-3
    %h3 New Customer
  .row
    .col-3
    .col-5
      %strong Name:
        = @customer.name
      %strong Age:
        = @customer.age
      %strong Phone no:
        = @customer.phone_no
      %strong Address:
        = @customer.address
    .col-4