config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'canteens/index'
  get 'canteens/:canteen_id/users', to: 'users#index_for_canteen_admin', as: 'canteen_admins'
  devise_for :users
  devise_scope :user do 
    match "/canteens/:canteen_id/invitations/new", :to => "users/invitations#new", :via => "get", :as => "new_canteen_invitation"
    #match "/canteens/:canteen_id/invitations/create", :to => "users/invitations#create", :via => "post", :as => "create_canteen_invitation"
  end
  root 'users#index'

  resources :csv_files
  resources :canteens do
    resources :users
    resources :customers do
      resources :attendance_details
      resource :membership do
        resources :payments
      end
  	end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :invitable
	validates :name, presence: true
	validates :role, inclusion: { in: %w(Admin CanteenAdmin), message: "%{value} is not a valid user" }
  belongs_to :canteen, optional: true

  before_validation do
  	self.role = 'CanteenAdmin' if role.blank?
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController

	def new
		@canteen = Canteen.find params[:canteen_id]
		super
	end

	def resource_params
    params.require(:user).permit(:name, :email,
    	:invitation_token, :canteen_id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def index_for_canteen_admin
  	@canteen = Canteen.find(params[:canteen_id])
  	@users = @canteen.users.all
  end

  def new
  	@canteen = Canteen.find(params[:canteen_id])
  	@user = @canteen.users.new
  end

  def create
  	@canteen = Canteen.find(params[:canteen_id])
    @user = @canteen.users.create(user_params)
    redirect_to canteens_path
  end

  def edit
  	@canteen = Canteen.find(params[:canteen_id])
  	@user = @canteen.users.find(params[:id])
  end

  def update
  	@canteen = Canteen.find(params[:canteen_id])
 		@user = @canteen.users.find(params[:id])
    if @user.update(user_params)
      redirect_to canteen_admins_path(@canteen)
  	else
    	render 'edit'
  	end
  end

  def destroy
  	@canteen = Canteen.find(params[:canteen_id])
  	@user = @canteen.users.find(params[:id])
  	@user.destroy
 
  	redirect_to canteen_admins_path(@canteen)
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password)
  	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for [@canteen, @user] do |f|
  = f.input :name, label: 'Enter canteen admin name'
  = f.input :email
  = f.input :password
  = f.button :submit, 'Save', class: 'btn btn-sm btn-success'
  = link_to 'Back', canteen_admins_path(@canteen), class: 'btn btn-sm btn-dark'

app/views/users/edit.html.haml
.container
  .row
    .col-3 
    %h3 Edit Canteen Admin
  .row
    .col-3
    .col-5
      =render 'form'
    .col-4

app/views/users/index.html.haml
.container
  .row.mt-5.ml-5 
    %h1 A customer management system for canteen admins
    %h2 Login & manage!
  .row.mt-3.ml-5
    - unless user_signed_in?
      = link_to "Login", new_user_session_path, class: 'btn btn-primary btn-lg'

app/views/users/index1.html.haml
.container
  .row.mb-3.mt-5
    .col-9
      %h3 Listing Admins
    .col-3
      = link_to 'Invite Admin', new_canteen_invitation_path(@canteen), class: 'btn btn-primary btn-md'

  %table.table.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Email
        %th Actions
    %tbody
      - @users.each do |user|
        %tr
          %td= user.name
          %td= user.email
          %td 
            =link_to 'Edit', edit_canteen_user_path(@canteen, user), class: 'btn btn-secondary btn-sm'
            =link_to 'Destroy', canteen_user_path(@canteen, user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'
  = link_to 'Back', canteens_path, class: 'btn btn-sm btn-dark'

app/views/users/index_for_canteen_admin.html.haml
.container
  .row.mb-3.mt-5
    .col-9
      %h3 Listing Admins
    .col-3
      = link_to 'Invite Admin', new_canteen_invitation_path(@canteen), class: 'btn btn-primary btn-md'

  %table.table.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Email
        %th Actions
    %tbody
      - @users.each do |user|
        %tr
          %td= user.name
          %td= user.email
          %td 
            =link_to 'Edit', edit_canteen_user_path(@canteen, user), class: 'btn btn-secondary btn-sm'
            =link_to 'Destroy', canteen_user_path(@canteen, user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'
  = link_to 'Back', canteens_path, class: 'btn btn-sm btn-dark'

app/views/users/new.html.haml
.container
  %br/
  .row
    .col-3 
    %h1 Add Canteen Admin
    .col-2
      - if user_signed_in?
        %button.btn.btn-link{:type => "button"}= link_to "Sign Out", destroy_user_session_path, method: :delete
  .row
    .col-3
    =render 'form'
  .row
    .col-3
    %button.btn.btn-primary.btn-md{:type => "button"}= link_to 'Back', canteens_path, class:"button-font-color"